matrix:
  include:
    - name: linux-py36
      language: python
      python: 3.6
      sudo: required
      services:
        - docker
      env:
        - CIBW_BUILD=cp36-*
    - name: linux-py37
      language: python
      python: 3.7
      dist: focal
      sudo: required
      services:
        - docker
      env:
        - CIBW_BUILD=cp37-*
    - name: linux-py37
      arch: arm64
      language: python
      python: 3.7
      dist: focal
      sudo: required
      services:
        - docker
      env:
        - PIP_NO_CACHE_DIR=off
        - CIBW_BUILD=cp37-manylinux_aarch64
      install:
        - python -m pip install -U pip
        - python -m pip install cibuildwheel==1.7.4
        - python -m pip install codecov tox twine
      script:
        - tox tests
        - codecov
        - git config --global user.email "junk@junk.com"
        - git config --global user.name "junk"
        - git stash --all # Restore fresh checkout
        - cibuildwheel --output-dir dist
    - name: linux-py38
      language: python
      python: 3.8
      dist: focal
      sudo: required
      services:
        - docker
      env:
        - CIBW_BUILD=cp38-*
    - name: linux-py38
      arch: arm64
      language: python
      python: 3.8
      dist: focal
      sudo: required
      services:
        - docker
      env:
        - PIP_NO_CACHE_DIR=off
        - CIBW_BUILD=cp38-manylinux_aarch64
      install:
        - python -m pip install -U pip
        - python -m pip install cibuildwheel==1.7.4
        - python -m pip install codecov tox twine
      script:
        - tox tests
        - codecov
        - git config --global user.email "junk@junk.com"
        - git config --global user.name "junk"
        - git stash --all # Restore fresh checkout
        - cibuildwheel --output-dir dist

    - name: linux-py39
      language: python
      python: 3.9
      dist: focal
      sudo: required
      services:
        - docker
      env:
        - CIBW_BUILD=cp39-*
    - name: linux-py39
      arch: arm64
      language: python
      python: 3.9
      dist: focal
      sudo: required
      services:
        - docker
      env:
        - PIP_NO_CACHE_DIR=off
        - CIBW_BUILD=cp39-manylinux_aarch64
      install:
        - python -m pip install -U pip
        - python -m pip install cibuildwheel==1.7.4
        - python -m pip install codecov tox twine
      script:
        - tox tests
        - codecov
        - git config --global user.email "junk@junk.com"
        - git config --global user.name "junk"
        - git stash --all # Restore fresh checkout
        - cibuildwheel --output-dir dist
    - name: osx-py36
      os: osx
      osx_image: xcode12.2
      language: generic
      env:
        - CIBW_BUILD=cp36-*
        - CIBW_TEST_COMMAND="pushd {project}; tox tests ; popd"
        - CIBW_BEFORE_BUILD="python -m pip install -U pip; python -m pip install tox twine"
      install:
        - python3 -m pip install cibuildwheel==1.7.4
        - python3 -m pip install twine
      script:
        - cibuildwheel --output-dir dist
    - name: osx-py37
      os: osx
      osx_image: xcode12.2
      language: generic
      env:
        - CIBW_BUILD=cp37-*
        - CIBW_TEST_COMMAND="pushd {project}; tox tests ; popd"
        - CIBW_BEFORE_BUILD="python -m pip install -U pip; python -m pip install tox twine"
      install:
        - python3 -m pip install cibuildwheel==1.7.4
        - python3 -m pip install twine
      script:
        - cibuildwheel --output-dir dist
    - name: osx-py38
      os: osx
      osx_image: xcode12.2
      language: generic
      env:
        - CIBW_BUILD=cp38-*
        - CIBW_TEST_COMMAND="pushd {project}; tox tests ; popd"
        - CIBW_BEFORE_BUILD="python -m pip install -U pip; python -m pip install tox twine"
      install:
        - python3 -m pip install cibuildwheel==1.7.4
        - python3 -m pip install twine
      script:
        - cibuildwheel --output-dir dist
    - name: osx-py39
      os: osx
      osx_image: xcode12.2
      language: generic
      env:
        - CIBW_BUILD=cp39-*
        - CIBW_TEST_COMMAND="pushd {project}; tox tests ; popd"
        - CIBW_BEFORE_BUILD="python -m pip install -U pip; python -m pip install tox twine"
      install:
        - python3 -m pip install cibuildwheel==1.7.4
        - python3 -m pip install twine
      script:
        - cibuildwheel --output-dir dist
install:
  - python -m pip install -U pip
  - python -m pip install cibuildwheel==1.7.4
  - python -m pip install codecov tox twine
script:
  - tox tests
  - codecov
  - git config --global user.email "junk@junk.com"
  - git config --global user.name "junk"
  - git stash --all # Restore fresh checkout
  - cibuildwheel --output-dir dist
deploy:
  - provider: pypi
    # server: https://test.pypi.org/legacy/
    user: jgu
    password:
      secure: "K1HppGu970i6WBKfnjQbCo0A0cYPih2rfM/rIDRzQXS8t+ZckyBywiKq/+4pkNJAfaHhQ8bHSz2J1GCq3Wz6DloGFHqEKAoHy5OgJxaK5nEp6avYvyHBSxrcZ6UfwFGMMMTAy4vfhnoJ3ARHaUFE4EIWYCVvP8/yCsE/6ir8AfozTssdYTUioJaYjSnowJ38nqa8H3hK3K5gke8aeclB+lnnWcyakgot65MfL2ov2mkkpWeiEn44ldV2iRKcl9a7Utgq3tJ1A634eUiNvIPpBYxnxPe++VRHA/mov9BWX0XfTmDuiVr+zDgMWdt3BK7f21r6P5DndpCZb8C2WzBFMKVz+rbuspbVJTol9Nt/9sVvSS6/fEBpXooRHRr9nP9EIt8Jlyv4CZ3iX/+T/912s84ZQCgqrhFNnRvECpmiVtHg49GecnMtJqC4jW57527c//oQPFyv/84Fd7fZ5jZg4LwhCl1C04Sqjmx8MFuMCR829CcZXJ2dAa5hQ/1v44SJAOKCQ0zDSdTqAy6x9RK/KNxnoQ9Nbn6ZFBUcjKx6rofyvXlwIcsQsjuzLw2mqmavZPduavVRi6cxK1WCEnaBVOXODWUSDatWchch1OcBm46X9UwwnHTsDHCVh6Bw+BDXhZuNw/72UA8z0sU/Val8iXBeThu33PMh3fo+uoqDf1g="
    distributions: "sdist"
    skip_existing: true
    skip_cleanup: true
    on:
      branch: master
      tags: true
