matrix:
  include:
    - name: linux-py27
      language: python
      python: 2.7
      sudo: required
      services:
        - docker
      env:
        - PIP=pip
        - CIBW_BUILD=cp27-*
    - name: linux-py34
      language: python
      python: 3.4
      sudo: required
      services:
        - docker
      env:
        - PIP=pip
        - CIBW_BUILD=cp34-*
    - name: linux-py35
      language: python
      python: 3.5
      sudo: required
      services:
        - docker
      env:
        - PIP=pip3
        - CIBW_BUILD=cp35-*
    - name: linux-py36
      language: python
      python: 3.6
      sudo: required
      services:
        - docker
      env:
        - PIP=pip3
        - CIBW_BUILD=cp36-*
    - name: linux-py37
      language: python
      python: 3.7
      dist: xenial
      sudo: required
      services:
        - docker
      env:
        - PIP=pip3
        - CIBW_BUILD=cp37-*
    - name: osx-py27
      os: osx
      language: generic
      env:
        - PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:$PATH"
        - PIP=pip
        - CIBW_BUILD=cp27-*
        - CIBW_TEST_COMMAND="pytest {project}/tests"
        - CIBW_BEFORE_BUILD="${PIP} install -U pip; ${PIP} install .; $PIP install .[tests]"
      install:
        - ${PIP} install cibuildwheel==0.10.0
      script:
        - cibuildwheel --output-dir dist
    - name: osx-py34
      os: osx
      language: generic
      env:
        - PIP=pip2
        - CIBW_BUILD=cp34-*
        - CIBW_TEST_COMMAND="pytest {project}/tests"
        - CIBW_BEFORE_BUILD="${PIP} install -U pip; ${PIP} install .; $PIP install .[tests]"
      install:
        - ${PIP} install cibuildwheel==0.10.0
      script:
        - cibuildwheel --output-dir dist
    - name: osx-py35
      os: osx
      language: generic
      env:
        - PIP=pip2
        - CIBW_BUILD=cp35-*
        - CIBW_TEST_COMMAND="pytest {project}/tests"
        - CIBW_BEFORE_BUILD="${PIP} install -U pip; ${PIP} install .; $PIP install .[tests]"
      install:
        - ${PIP} install cibuildwheel==0.10.0
      script:
        - cibuildwheel --output-dir dist
    - name: osx-py36
      os: osx
      language: generic
      env:
        - PIP=pip2
        - CIBW_BUILD=cp36-*
        - CIBW_TEST_COMMAND="pytest {project}/tests"
        - CIBW_BEFORE_BUILD="${PIP} install -U pip; ${PIP} install .; $PIP install .[tests]"
      install:
        - ${PIP} install cibuildwheel==0.10.0
      script:
        - cibuildwheel --output-dir dist
    - name: osx-py37
      os: osx
      language: generic
      env:
        - PIP=pip2
        - CIBW_BUILD=cp37-*
        - CIBW_TEST_COMMAND="pytest {project}/tests"
        - CIBW_BEFORE_BUILD="${PIP} install -U pip; ${PIP} install .; $PIP install .[tests]"
      install:
        - ${PIP} install cibuildwheel==0.10.0
      script:
        - cibuildwheel --output-dir dist
install:
  - ${PIP} install -U pip
  - ${PIP} install -r docs/requirements.txt
  - ${PIP} install cibuildwheel==0.10.0
  - ${PIP} install .[flake8]
  - ${PIP} install codecov
script:
  - flake8 --ignore=E501 lz4
  - flake8 --ignore=E501 tests
  - flake8 --ignore=E501 setup.py
  - ${PIP} install .[tests]
  - ${PIP} install -e . # This needs to be IMMEDIATELY before coverage tests
  - pytest --cov=lz4 tests # coverage run --source=lz4 -m pytest tests
  - make -C docs doctest html
  - codecov
  - git stash --all # Restore fresh checkout
  - cibuildwheel --output-dir dist
deploy:
  - provider: pypi
    # server: https://test.pypi.org/legacy/
    user: jgu
    password:
      secure: "K1HppGu970i6WBKfnjQbCo0A0cYPih2rfM/rIDRzQXS8t+ZckyBywiKq/+4pkNJAfaHhQ8bHSz2J1GCq3Wz6DloGFHqEKAoHy5OgJxaK5nEp6avYvyHBSxrcZ6UfwFGMMMTAy4vfhnoJ3ARHaUFE4EIWYCVvP8/yCsE/6ir8AfozTssdYTUioJaYjSnowJ38nqa8H3hK3K5gke8aeclB+lnnWcyakgot65MfL2ov2mkkpWeiEn44ldV2iRKcl9a7Utgq3tJ1A634eUiNvIPpBYxnxPe++VRHA/mov9BWX0XfTmDuiVr+zDgMWdt3BK7f21r6P5DndpCZb8C2WzBFMKVz+rbuspbVJTol9Nt/9sVvSS6/fEBpXooRHRr9nP9EIt8Jlyv4CZ3iX/+T/912s84ZQCgqrhFNnRvECpmiVtHg49GecnMtJqC4jW57527c//oQPFyv/84Fd7fZ5jZg4LwhCl1C04Sqjmx8MFuMCR829CcZXJ2dAa5hQ/1v44SJAOKCQ0zDSdTqAy6x9RK/KNxnoQ9Nbn6ZFBUcjKx6rofyvXlwIcsQsjuzLw2mqmavZPduavVRi6cxK1WCEnaBVOXODWUSDatWchch1OcBm46X9UwwnHTsDHCVh6Bw+BDXhZuNw/72UA8z0sU/Val8iXBeThu33PMh3fo+uoqDf1g="
    distributions: "sdist"
    skip_existing: true
    skip_cleanup: true
    on:
      branch: master
      tags: true

