# See:
# https://packaging.python.org/appveyor/
# https://github.com/ogrisel/python-appveyor-demo
# https://www.appveyor.com/docs/appveyor-yml/
# https://packaging.python.org/appveyor/

environment:

  matrix:

    - PYTHON: "C:\\Python27-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"

matrix:
  # Immediately finish build once one of the jobs fails.
  fast_finish: true

platform: x64

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

  # Prepend relevant Python installation to the PATH. Also prepend the location
  # of the build.cmd file.
  - "SET PATH=%CD%\\appveyor;%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "build.cmd python --version"
  - "build.cmd python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "build.cmd python -m pip install --disable-pip-version-check --user --upgrade pip"

  # We need wheel installed to build wheels, and this isn't pulled in by setup.py
  - "build.cmd python -m pip install wheel"

  # We need tox to run tests
  - "build.cmd python -m pip install tox"

build_script:
  # Build the compiled extension
  - "build.cmd python setup.py build"

test_script:
  # Run the project tests. Test only for 64 bit Python as the 32 bit tests fail
  # due to memory fragmentation resulting from many alloc/free cycles
  # ps: $env:is64bit = $env:PYTHON.Contains("-x64")
  # IF %is64bit% == True build.cmd tox
  - "build.cmd tox"

after_test:
  # If tests are successful, create binary packages for the project.
  - "build.cmd python setup.py bdist_wheel"
  - ps: "ls dist"

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
#
